### ISSUE TITLE
Places in Philharmonie that are not in Philharmonie

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/euterpe-converter#5]
List of places that **WRONGLY** `P89 falls within` Philharmonie de Paris.
https://docs.google.com/spreadsheets/d/130yI9C2_8EUc1E9dXcH2eZPl2U95JO68WlPU9pmw724
> The list is from April, the links are changed in the meanwhile BUT it is easy search the label directly in the facet browser.

-- issued by @ccecconi

**Comment by pasqLisena** [comment]
Example: Poulenc Story in _Salle d'Orgue_
http://data.doremus.org/performance/d6dc221a-f763-3c23-bc38-0ed95f094b70

Source file:

        <evenement>
            <etablissement>Philharmonie de Paris</etablissement>
            <lieu>Salle d'orgue</lieu>
            <id>18284</id>
            <titre_ligne1>Poulenc story</titre_ligne1>
            <titre_ligne2>Orchestre de Mulhouse - Ariane Matiakh - Karol Mossakowski</titre_ligne2>
            <representations>
            ....

The `etablissement` is Philharmonie de Paris in the source!
So this is actually a bug in the sources? Do I have to apply a workaround for exactly those cases that are in the table?

**Comment by pierrechoffe** [comment]
hi @pasqLisena , I had not seen this conversation, and I don't know if you received any answer to your question. So just in case you didn't, my answer would be that the Philharmonie de Paris is the organizer, the global institution that produces the concerts (and much more), whereas "Salle d'orgue" is the place where the performance took place. In most cases the difference should be easy to spot, but I don't know how they label the big concert hall: if they label it "Philharmonie de Paris", then there may be some confusion. Only @ccecconi can say.

**Comment by pasqLisena** [comment]
Hello Pierre,
I found an answer [here](https://docs.google.com/spreadsheets/d/1ShZEEwQKcF36HhBHwviP8rsBG48vAlNtnn9AO6lH7hk/edit#gid=408842201) (line 7), so I applied a workaround not considering the `etablissement` in the cases specified in the [list](https://docs.google.com/spreadsheets/d/130yI9C2_8EUc1E9dXcH2eZPl2U95JO68WlPU9pmw724/edit)
