### ISSUE TITLE
Empty labels

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/euterpe-converter#6]
What to do with empty labels?

```sparql
select * where { graph ?g {?s rdfs:label ""}}
```
[results](http://data.doremus.org/sparql?default-graph-uri=&query=select+*+where+%7B+graph+%3Fg+%7B%3Fs+rdfs%3Alabel+%22%22%7D%7D&should-sponge=&format=text%2Fhtml&timeout=0&debug=on)

**Comment by rtroncy** [comment]
There seems to be two different cases:
 - [x] entities of type F11_Corporate_Body, so I assume ensembles. Why don't we have a label? Bad parsing? I'm surprised to not see any provenance attached to this [artist](http://data.doremus.org/artist/bfda9618-54c3-37ee-a4c2-e02f4942bffe)
 - [x] entities of type F22_Self-Contained_Expression. Again, is it due to a bad parsing?

**Comment by pasqLisena** [comment]
> I'm surprised to not see any provenance attached to this artist

I am currently adding the provenance only to the main entity described. In the case of Euterpe records, the foreseen performance.

**Comment by pasqLisena** [comment]
The parsing is correct.

Examples:
1. http://data.doremus.org/expression/d20dcb24-0740-3119-8164-d020b72eab67

In ` Sept 2008-Juin 2016-Euterpe-Evenements Philharmonie.xml`
```xml           
<oeuvre>
      <id>13490</id>
     <titre></titre>
     <compositeurs>
         <compositeur id="10638">Mauro Lanza</compositeur>
     </compositeurs>
 </oeuvre>
```

2. http://data.doremus.org/artist/bfda9618-54c3-37ee-a4c2-e02f4942bffe
referred to http://data.doremus.org/performance/74c46623-7618-398d-a451-64e043d4fdaa
In ` Sept 2008-Juin 2016-Euterpe-Evenements Philharmonie.xml`

```xml
        <evenement>
            <etablissement>Cité de la musique</etablissement>
            <lieu>Salle des concerts</lieu>
            <id>14557</id>
            <titre_ligne1>Charles Bradley / Nick Waterhouse</titre_ligne1>
            <titre_ligne2 />
            <representations>
                <date>mercredi 03/09/2014, 20:00</date>
            </representations>
            <activites>
                <activite activite_id="1">concert</activite>
            </activites>
            <genres>
                <genre genre_id="7">Jazz</genre>
                <genre genre_id="9">Rock, Pop, Soul</genre>
            </genres>
            <lien_web>http://www.citedelamusique.fr/francais/activite/concert/14557</lien_web>
            <distribution>
                <formation id="2618">Nick Waterhouse</formation>
                <formation id="2266">  </formation>
                <formation id="2267">   </formation>
                <formation id="2619">Charles Bradley</formation>
            </distribution>
          ....
```

**Comment by rtroncy** [comment]
Thanks for having checked. So, indeed, we should ask Philharmonie what to do in this case. cc @ccecconi

**Comment by pasqLisena** [comment]
- the f22s will become f22s without a title
- ensembles are not converted at all
